name: build-and-push
on:
  schedule: [{ cron: "0 6 * * *" }]  # daily (6am UTC)
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ github.repository_owner }}/mbbsemu:latest
          # optionally pass a pinned tag:
          # build-args: |
          #   MBBSEMU_VERSION=v1.0-alpha-123023
